--- #YAML:1.0
name:               Linux-Personality
version:            0.01
abstract:           Perl interface to the personality(2) Linux system call.
author:
    - Steffen Schwigon <ss5@nonet>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
